# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ecc.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = r"C:\Users\chith\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\Lib\site-packages\PyQt5\Qt5\plugins\platforms"




class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.txt_infor = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_infor.setGeometry(QtCore.QRect(200, 200, 421, 87))
        self.txt_infor.setObjectName("txt_infor")
        self.txt_sig = QtWidgets.QTextEdit(self.centralwidget)
        self.txt_sig.setGeometry(QtCore.QRect(200, 300, 421, 87))
        self.txt_sig.setObjectName("txt_sig")
        self.btn_sign = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sign.setGeometry(QtCore.QRect(210, 440, 93, 28))
        self.btn_sign.setObjectName("btn_sign")
        self.btn_ve = QtWidgets.QPushButton(self.centralwidget)
        self.btn_ve.setGeometry(QtCore.QRect(510, 440, 93, 28))
        self.btn_ve.setObjectName("btn_ve")
        self.btn_gen_ks = QtWidgets.QPushButton(self.centralwidget)
        self.btn_gen_ks.setGeometry(QtCore.QRect(520, 150, 93, 28))
        self.btn_gen_ks.setObjectName("btn_gen_ks")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(320, 50, 191, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 200, 81, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(110, 310, 81, 16))
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_sign.setText(_translate("MainWindow", "Sign"))
        self.btn_ve.setText(_translate("MainWindow", "Verify"))
        self.btn_gen_ks.setText(_translate("MainWindow", "Generate Keys"))
        self.label.setText(_translate("MainWindow", "ECC CIPHER"))
        self.label_2.setText(_translate("MainWindow", "Information:"))
        self.label_3.setText(_translate("MainWindow", "Signature:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
